language: android
jdk: oraclejdk8
android:
  components:
  - tools
  - platform-tools
  - build-tools-25.0.3
  - android-25
  - extra-google-m2repository
  - extra-android-m2repository
  licenses:
  - android-sdk-license-.+
script:
- "./gradlew build"
before_install:
- chmod +x gradlew
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
after_failure:
- cat app/build/reports/tests/testDebugUnitTest/index.html
- cat trakt-api/build/reports/tests/testDebugUnitTest/index.html
env:
  global:
  - secure: BMUfc+8yof5C31geyXdoo9++PoKEPwLUDj2SUAD6UFtsMDAyPS8t0iLCt1e5EEQ4L7ulz4h527rgVJHHg38P0y+iLsHsObQrunHbCbDg5LJFn/3XwmNCmAD25SPY1Lst7HxzDM4hdnmskV3/McCvmI+XJOLei0C8OkNFtGocTAR9q2aVpq1x3bTEQyWI7JBSrdJix2opn5Av2W+2immnmVsE6ah6mhupYd9hvOUT5uk+dbygoeNqhUxaSPEe+GQ5ttMSfRHeBJMrIzHt72IxYmx8CUyL2GwgcShk77o8m0/vEPjiee/lFpDJQF1TED2JUm8EcTzIjfjKU9oKaC+mM7oxwmZkmNP/DGHr75aGuRmwmkwP4GvNqMprTI7PEGD2SNrs3xbDPnpa3XnavOSAijNVRUxWkOKw+S7Ze7Tvmd11MSY0J+gCMMULmt9ypYi633MkZwFsmdOw1Le2QX1Im8lPWlYhx+41OkMyVlTLcegv0cst0k6GzNwuIHbWAkJujpZBXJsTaPuiTt04toW13PKACBSOT1b2FuSrpdH6a7jNf1pvbSkgpCevcVDXNfr26sUhRj3SSNujGIoer6Y/ODWfJb4qKI4lALH2BreU04Sg+69tW2Y4ontvtZWbQQCl9KtGJbehOOsUBG9JY1PK1t8enTqbFFNcGTkVdE1MYXw=
  - secure: byw4GgPlYTI4x3yG/vcaT+/3OZ1usOiEiaHwS66kjEzQCXTQO7sfS7sfB54cKxkJcIswXo64CM5onx8QpZklB+SbrbZJhZOuIpLr4LLluCecDHCm9lOVwt/qKrJcv6Omk6LV2fXqLDZa4A6fNtk4vKQwWrM3wvU5RdB4ea3b252qh1/FxsuI/ffLOUO5CkMYmDsKhjWEGVkaBbZRg2eWwTqZ4ATJ1TKTyG7eWo9BAcBC3pE640VKVkcAdCAkNf0X2rWzBB2iHv0EZkSBiRrybFw94e42DKjVPHxljm9WYR/fcWl6mojnQaj1dD0VGFWuT0t/g1LuSwn4qAsu37Y94LH4iM/Xa9Cy5tE8lfC/AGWUUn2F03tNv+kfpSCVU4Pklpw1qFGMgUmX7w/Hyy1TOx7DwVPFmd5kHMuAIvAloBJzlQTRBGD7h2dya5+Q8lB8gDB/bQZ5M9/C1BA2GDECH7X4HQMa3NOKB9V8YvVnv1nWawtjlKkpDCnecYBdEPalZxjemSQoU4C7IlMU1LOdvI71s25O6xD2Ya9eemjke3VsfSCDFxWdzcmJu6QsLA+aTYTZddoAeVHXo+AMipmSdt2r0eSrNS/ovaiVlcrAJzePe9eCjgCscGqJ5vjtXibK/40r3ek4pXXWe+IdCC8MyWzVEO/wcFNXi7XUZn6gPF8=
  - secure: gO6Ld5wyiuCXHrX82ihd/CXnxfTJe+B7GULrFdxpP7tEF6qd8+bK09Xf/8eNlCuu9AxtZQeQilqgJP3lL2KoiAmVOQd4uq6ya8gqfD9n2m1rVUQEEHZr2tad+vXoROzippLFEgTvwID7tyX2EMqg2DmxsT0z+OlEfzmAvXj/AOHegy7QEEhJkwk+04L/pVrfcEU08pEX7rGCWcSXZxMKaW58JJTTFug9wB003DLeS88RUG3ClS/2z0odes2GZGeqHK2iqvzfhIIaCYfQ6c7DOLA7wSZwE8AK11g7yS/3vaX1kUp/5h0ACwMaKUh9SBaHyAHHenQY7oLLwFD4X84zl2PTFkkJ+ePh9Yyck/+U4IDVIP/EOetpkxxpYNebPb+7rdsNtjXKEsMB77KE0A680PUzkDVwyoRoiWVvndZ4n8n7OwqwJ7NEvvBsJeR/zSHW000p5Uo6TCwbwAZOzuwgxpRMtHALb0PnMyMm64aCP4+dXOznw/jKFlPMiMk9jXmvnDDga14sGHRoeTxZGREgT55NEPFDlpfJ38d4kukQP7joiPWFqx2PcJe5NSxW7wlMY/VoQeNo2FUlk7Pk0J9SjRLPY8CqtpOzkblRhT5NxpWL76AhoPmfdV9SkqxsTmwThG/2MTYoDkvZtbcwx1EYgrJxvRUMsaPyjF3Q8KaDdBI=
  - trakt_baseURL=https://api.trakt.tv
  - fanart_baseURL=http://webservice.fanart.tv/v3/
